# Generated by Django 5.0 on 2023-12-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_sender_chatmessage_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='resource_files/')),
                ('url_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
